FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Hello Books API

Hello Books is a simple API designed to ease library systems functionalities. 
Actions like registering library clients, holding book information, allow users
to search and browse all books as well as borrow and return books. Each functionality
is implemented as an endpoint, all endpoints are listed as follows
allowing consumers to view polls and vote in them.

## Book Collection [/books]

### List All Books [GET]

+ Response 200 (application/json)

        [
            {
                "question": "Book Data",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "If tomorrow comes",
                        "author": "Sidney Sheldon",
                        "votes": 2048
                    }, {
                        "choice": "Origin",
                        "author": "Ken Follet",
                        "votes": 1024
                    }, {
                        "choice": "The preamble",
                        "author": "Ngoso 101",
                        "votes": 512
                    }, {
                        "choice": "The Junction",
                        "author": "William Mbadi",
                        "votes": 256
                    }
                ]
            }
        ]

### Add a new Book [POST]

You can add a new book entry into the collection.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }